### ISSUE TITLE
Create POST route to read data

### ISSUE THREAD

**Issue by YashKumarVerma** [ACM-VIT/dolos#12]
Create a POST route that responds to requests made on `api/v1/generate` and reads the request body as a JSON.

To be done after #11

**Comment by vj-abishek** [comment]
@YashKumarVerma can I work on it?

**Comment by vj-abishek** [comment]
> Create a POST route that responds to requests made on `api/v1/generate` and reads the request body as a JSON.
> 
> To be done after #11

What needs to be done to the result?

**Comment by DreamsOfImran** [comment]
@YashKumarVerma, Created PR for it. Please review.
https://github.com/ACM-VIT/dolos/pull/21

**Comment by YashKumarVerma** [comment]
@vj-abishek please send a pr directly as these are very small code changes. I'm opening more issues, hope that you would find some suitable to solve.

**Comment by YashKumarVerma** [comment]
Done in #21
