### ISSUE TITLE
Add Eslint and prettier for code quality.

### ISSUE THREAD

**Issue by jabbar86** [ACM-VIT/dolos#19]
Adding ESLint will be helpful in identifying some common and uncommon mistakes that are made during coding.

**Comment by JoelLau** [comment]
hi @jabbar86, can i take this up as part hacktoberfest?

also, are there any specific settings you would like to include?

**Comment by jabbar86** [comment]
@JoelLau  Sure. Just keep a few things in mind 

add prettier and eslint while committing any changes. You can use husky for this if you are aware.

**Comment by YashKumarVerma** [comment]
Please send a PR directly, we won't be assigning the issue to individuals.

**Comment by vj-abishek** [comment]
@YashKumarVerma Done. Here is the PR #33
