### ISSUE TITLE
Add .env.example

### ISSUE THREAD

**Issue by YashKumarVerma** [ACM-VIT/dolos#28]
new users might find it difficult to set up the project, plus it's always good to mention all environment variables being used in the project in one place. 

Add a `.env.example` file with a list of all environment variables that the project uses. 

Hint: they're used as process.env.xyz

**Comment by hauze-v** [comment]
Hi there, I should be able to do this for you, may you assign to me?

**Comment by YashKumarVerma** [comment]
Please note that we cannot merge a separate PR for this issue, as this might fall violate the principles established by HacktoberFest.

If you wish to fix this issue, please club this with some other issue.

**Comment by hauze-v** [comment]
Just go with @archonn, he clearly wants it.
