### ISSUE TITLE
Fix CI Build

### ISSUE THREAD

**Issue by YashKumarVerma** [ACM-VIT/dolos#37]
The build is failing for the project, take measures, play with code to pass it / get it working.

**Comment by umer2001** [comment]
Hi,
can I try to help with this ?

**Comment by YashKumarVerma** [comment]
sure, I guess the ci is still broken. try @umer2001

**Comment by umer2001** [comment]
@YashKumarVerma , I think the problem is in coding part or Testing part, not in the CI workflow

**Comment by YashKumarVerma** [comment]
@umer2001 the CI did not have database service, fixed in #61
