### ISSUE TITLE
Add Pull Request Templates

### ISSUE THREAD

**Issue by YashKumarVerma** [ACM-VIT/dolos#38]
The project is getting pull requests daily, ensure that we have a proper pull request template.

**Comment by shreyaskj** [comment]
assign this to me @YashKumarVerma

**Comment by YashKumarVerma** [comment]
send a PR @shreyaskj

**Comment by xNetcat** [comment]
we can close this #43

**Comment by shreyaskj** [comment]
can you open this, I will take this up @YashKumarVerma

**Comment by YashKumarVerma** [comment]
this has been resolved.
