### ISSUE TITLE
Trim Readme to keep relevant content

### ISSUE THREAD

**Issue by YashKumarVerma** [ACM-VIT/dolos#39]
Move content from the readme that discusses how to contribute, and place it in a separate file in the docs folder / or put it as CONTRIBUTING GUIDELINES (check, GitHub has something specific for that).

**Comment by M4yankChoudhary** [comment]
can i take this ?

**Comment by PravunathSingh** [comment]
Hey, @YashKumarVerma can I work on this issue? I can start working on it immediately.

**Comment by YashKumarVerma** [comment]
@M4yankChoudhary @PravunathSingh yes, it's open.
