### ISSUE TITLE
Write schema processor

### ISSUE THREAD

**Issue by YashKumarVerma** [ACM-VIT/dolos#41]
Write a function which accepts the schema (JSON body) sent by the user and determines which type of data to fill

**Comment by Brainshaker95** [comment]
I would like to work on this issue. Could you please elaborate a bit more?

**Comment by YashKumarVerma** [comment]
the user would send a json object, in the format of 
```JSON
{
	"name":"string",
	"age":"number",
	"gender": ["male", "female", "other"]
	....
}
```

the function should parse this object and determine which type of data is to be inserted

**Comment by Brainshaker95** [comment]
So you just want the function to return an object like this?

```js
{
	name: "string",
	age: "number",
	gender: "object",
}
```

Or what exactly do you mean when you say "type"?
Sorry if this is obvious, but I'm not sure what you mean.
