### ISSUE TITLE
Use for-the styled badge for Github Actions

### ISSUE THREAD

**Issue by YashKumarVerma** [ACM-VIT/dolos#42]
Ensure that all the badges are in the same format

![image](https://user-images.githubusercontent.com/14032427/95225705-b0e60000-0819-11eb-837f-506939d62ccd.png)

**Comment by a-mere-peasant** [comment]
Hey, can I help with this ?

**Comment by YashKumarVerma** [comment]
@a-mere-peasant please read guidelines

**Comment by xNetcat** [comment]
we can close this #43
